"""Idea Generation Cloud - Generative AI creating 1000 ideas"""
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

plt.rcParams.update({
    'font.size': 10, 'axes.labelsize': 10, 'axes.titlesize': 11,
    'xtick.labelsize': 9, 'ytick.labelsize': 9, 'legend.fontsize': 9,
    'figure.figsize': (10, 6), 'figure.dpi': 150
})

np.random.seed(42)
fig, ax = plt.subplots(figsize=(10, 6))

# Generate 1000 idea points in a cloud pattern
n_points = 1000
theta = np.random.uniform(0, 2 * np.pi, n_points)
r = np.random.exponential(2, n_points)
x = r * np.cos(theta) + np.random.normal(0, 0.3, n_points)
y = r * np.sin(theta) + np.random.normal(0, 0.3, n_points)

# Color by distance from center (innovation quality)
distances = np.sqrt(x**2 + y**2)
colors = plt.cm.viridis(1 - distances / distances.max())

ax.scatter(x, y, c=colors, s=15, alpha=0.6, edgecolors='none')

# Highlight some key idea clusters
cluster_centers = [(2, 1.5), (-1.5, 2), (-2, -1), (1, -2), (0, 0)]
cluster_labels = ['Climate\nLeaders', 'Social\nImpact', 'Governance\nFocus', 'ESG\nMomentum', 'Balanced\nApproach']

for (cx, cy), label in zip(cluster_centers, cluster_labels):
    ax.scatter(cx, cy, s=200, c='#e74c3c', alpha=0.8, marker='*', edgecolors='white', linewidth=1)
    ax.annotate(label, (cx, cy), xytext=(cx + 0.5, cy + 0.5),
               fontsize=8, color='#e74c3c', fontweight='bold',
               arrowprops=dict(arrowstyle='->', color='#e74c3c', alpha=0.5))

ax.set_xlim(-6, 6)
ax.set_ylim(-5, 5)
ax.set_xlabel('Innovation Dimension 1', fontsize=10)
ax.set_ylabel('Innovation Dimension 2', fontsize=10)
ax.set_title('Generative AI: 1,000 Investment Thesis Ideas', fontsize=12, fontweight='bold', color='#2ecc71')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Add annotation
ax.text(5.5, -4.5, 'Each point = 1 idea\ngenerated by LLM', fontsize=8, ha='right', color='gray', style='italic')

plt.tight_layout()
plt.savefig(Path(__file__).parent / 'chart.pdf', dpi=300, bbox_inches='tight')
plt.savefig(Path(__file__).parent / 'chart.png', dpi=150, bbox_inches='tight')
plt.close()
print("06_idea_generation created")
